### ISSUE TITLE
Can´t find and use Services

### ISSUE THREAD

**Issue by Bastiman75** [frenck/spook#105]
Using HomeAssistant
Home Assistant 2023.3.6
Supervisor 2023.03.3
Operating System 9.5
Frontend 20230309.1 - latest

with

Spook V0.11.1117 installed via HACS
and also tried the manual installation.

Tried to use 
Service: Disable an integration
and
Service: Enable an integration

but i can´t find

homeassistant.disable_config_entry
or
homeassistant.enable_config_entry

in HomeAssistant / Developer Tools / Services.

**Comment by frenck** [comment]
🤷 

Have you added the integration? (which you should not do)

../Frenck
