### ISSUE TITLE
Input_number.decrease is incrementing

### ISSUE THREAD

**Issue by luismalves** [frenck/spook#115]
Hi! Thank you for this integration!

As the title says, and by looking at the code, it seems there a typo in the math sign. Decrement should remove the amount and is adding.

I'm not providing an amount to the service call.

Thanks!

**Comment by DurgNomis-drol** [comment]
#114 fixes your issue, until a new release is made. You can just use -1 as the amount

**Comment by frenck** [comment]
Closing, as it was fixed in #114
