### ISSUE TITLE
Remove all orphaned entities 👻 not working

### ISSUE THREAD

**Issue by Frankster-NL** [frenck/spook#20]
I tried to use the remove all orphaned entities service call, but this apparently does not result into any actions. When looking in the debug log there is also nothing that refers to any actions.

**Comment by frenck** [comment]
Cool, but... this is like saying... "My car doesn't start, what is the issue?"

Please provide information. E.g., what is the state of the entity currently you expected to be removed? Could you provide an state dump from the dev tools from it?

../Frenck

**Comment by bkbartk** [comment]
no support so I'm going to ask anyway ;)

I experience the same issue
I run

```
service: homeassistant.delete_all_orphaned_entities
data: {}
```
from dev tools services
![image](https://github.com/frenck/spook/assets/17070805/077d24c3-62c3-4aaa-8454-6d03f10f090c)

And in my entities still unavailable entities remain
![image](https://github.com/frenck/spook/assets/17070805/be98ba5e-4060-4c23-ae94-51dd5d08bff8)
this is one example, but it's all of them,

a lot of entities I renamed in esp but didn't bother to remove the old naming.

![image](https://github.com/frenck/spook/assets/17070805/2345ce83-5208-4654-8170-358aef2869a3)
and I think you might need this
![image](https://github.com/frenck/spook/assets/17070805/29376dd5-17d9-4a58-a487-153139cb5055)

or this
![image](https://github.com/frenck/spook/assets/17070805/0e78ae65-d995-4a98-949a-fd02757639f6)


thank you for the support you've promised not to give on an integration that shouldn't work.

**Comment by frenck** [comment]
> And in my entities still unavailable entities remain

That is not an orphaned entity. So, correct that it isn't removed.

**Comment by frenck** [comment]
At this point, there is nothing in this issue indicating a bug.

Going to close this for now.

../Frenck
