### ISSUE TITLE
Spook implicitly using device name

### ISSUE THREAD

**Issue by hmmbob** [frenck/spook#239]
Error says it all - happening on 2023.7.0b2

`Entity sensor.custom_integrations (<class 'custom_components.spook.ectoplasms.homeassistant.sensor.HomeAssistantSpookSensorEntity'>) is implicitly using device name by not setting its name. Instead, the name should be set to None, please report it to the custom integration author.`

I am not using Spook of course. That would be in violation of the terms. ;-)

**Comment by frenck** [comment]
Already fixed in #233, not released yet.

../Frenck
