### ISSUE TITLE
Services not found

### ISSUE THREAD

**Issue by mkwatchface** [frenck/spook#24]
Hello,

I have installed Spook on Home Assistant via HACS as i wanted to be able to use the enable/disable integration service in an automation. Unfortunately, after installing i tried to find the services in the Developer Tools and to my surprise they were not there. Of course i have restarted my Home Assistance instance multiple times.

Here is a few details more:

Home Assistant 2023.3.1
Supervisor 2023.01.1
Operating System 9.5
Frontend 20230302.0 - latest

Should you need more details please let me know!

Checked the logs as well but there is no error. Since this is the latest version of Home Assistance, is there a possibility that the integration is not working yet with the latest version?

Thanks

**Comment by frenck** [comment]
> possibility that the integration is not working yet with the latest version?

It works. Developing on top of 2023.4.0dev0 even.

Please enable debug logging for `custom_components.spook` to see more details.

**Comment by randybb** [comment]
Hehe, I had the same problem - after installation in HACS you need to add it as integration and after that it starts working :)
![obrázok](https://user-images.githubusercontent.com/206765/222780066-f3bd7322-df20-4a9e-91f9-035740422ace.png)

**Comment by frenck** [comment]
Good point @randybb!
Did you add / set up the integration @mkwatchface?

**Comment by mkwatchface** [comment]
I haven't! In the installation docs frenck mentioned that we shouldn't... Also, in the configuration section it was mentioned that all entities are enabled by default so we have a really bad time right from the start...

Jokes aside thank you very much for directing me there, it now works
