### ISSUE TITLE
input number services don't allow to select a input helper

### ISSUE THREAD

**Issue by Ladonize** [frenck/spook#25]
First: Many thanks for the wonderful Spook!

I use input number helpers in some automations. When I want to use 'Input number: Increase/Decrease value 👻' that replaced the HA services the entity list is populated with number sensors but no longer with the input_numbers. The entity list is correctly populated with the input numbers when using 'Input number: Set maximum/minimum value 👻'.

I figured I could just enter them in yaml mode but then the service simply doesn't do anything at all anymore. Previously working and not altered automations using this service aren't working either.

![Screenshot 2023-03-03 200450](https://user-images.githubusercontent.com/104278026/222805665-5d21dfb4-d325-432d-8b84-5f926a1e8480.jpg)
![Screenshot 2023-03-03 200605](https://user-images.githubusercontent.com/104278026/222805670-92002563-77ad-4c3a-87de-cb9d69856731.jpg)

I'm on 2023.3.1 and the latest spook.

**Comment by frenck** [comment]
Yeah, that is a bug. Sorry about that.

../Frenck

**Comment by Ladonize** [comment]
I love it that even for a product you clearly stated we shouldn't use and "integration comes with absolutely 0/zero/zip/nada/noppes support" still receives this level of support. Thank you Frenck!
