### ISSUE TITLE
Automatically remove solved issues 

### ISSUE THREAD

**Issue by dof250** [frenck/spook#261]
First of all, Spook has been pretty helpful in the past weeks so thanks for that! 

Not sure if I'm missing something, but whenever Spook shows me there is an issue and I fix the issue, the notification stays until I restart HA. Is there a way to have Spook "recheck" after I've solved the issue?

**Comment by frenck** [comment]
Thanks! 👻 

This I've already fixed in the upcoming rewrite 👍 

../Frenck
