### ISSUE TITLE
New Zone services do not work

### ISSUE THREAD

**Issue by martinhoess** [frenck/spook#310]
Unfortunately the new zone services do not work for me

![image](https://github.com/frenck/spook/assets/47973549/8d182423-e747-44f5-9d34-f1d630c2b504)

_Originally posted by @martinhoess in https://github.com/frenck/spook/discussions/155#discussioncomment-6705529_

**Comment by frenck** [comment]
Please... just use stuff as normal 🙏 

<https://github.com/frenck/spook/issues/new/choose>
