### ISSUE TITLE
New zone services do not work 

### ISSUE THREAD

**Issue by martinhoess** [frenck/spook#311]
### What version of Spook are you using?

1.1.0

### What version of Home Assistant are you using?

2023.8.1

### The problem

The new zone services that were implemented with the last version do not work.

```
service: zone.create
data:
  radius: 50
  name: Test
  icon: mdi:test-tube
  latitude: 46.123
  longitude: 14.321
```

### Anything in the logs? Paste it here!

```
Logger: homeassistant.helpers.script.websocket_api_script
Source: custom_components/spook/ectoplasms/zone/services/create.py:23
Integration: Spook (documentation, issues)
First occurred: 23:38:28 (1 occurrences)
Last logged: 23:38:28

websocket_api script: Error executing script. Unexpected error for call_service at pos 1: 'zone'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 468, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 703, in _async_call_service_step
    response_data = await self._async_run_long_action(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 665, in _async_run_long_action
    return long_task.result()
           ^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 1974, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2011, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 980, in admin_handler
    await result
  File "/config/custom_components/spook/ectoplasms/zone/services/create.py", line 23, in async_handle_service
    collection: ZoneStorageCollection = self.hass.data[DOMAIN]
                                        ~~~~~~~~~~~~~~^^^^^^^^
KeyError: 'zone'
```

**Comment by frenck** [comment]
Some question:
- Do you have the `zone.reload` service available on your system?
- Do you have zones configured besides the default Home zone at this point?
	-  If yes: Do you manage them via YAML or UI?

**Comment by martinhoess** [comment]
* Yes
* Yes
  * Mixed, the Home zone is configured via YAML and there are 2 more which where added via UI

**Comment by frenck** [comment]
Shit, there goes my possible theory 💩  I'm not fully understanding how this can happen to be honest. Need to dig a bit more and will report back.

../Frenck

**Comment by martinhoess** [comment]
I've removed the Home Zone from the yaml. And now the spook services work.

**Comment by frenck** [comment]
Ah! I see it in the code now... ok that needs better handling!

![CleanShot 2023-08-11 at 23 57 47](https://github.com/frenck/spook/assets/195327/2c2670b1-6098-402d-94c8-44db8f58c8d1)

If `zone.home` is there, it will just return and not set the data as I need in the last line.

Thank you so much for this, will address this... not sure how.. but I'll figure something out :)

../Frenck
