### ISSUE TITLE
Repairs name should be set to None

### ISSUE THREAD

**Issue by Anto79-ops** [frenck/spook#312]
### What version of Spook are you using?

1.1.0

### What version of Home Assistant are you using?

2023.8.2

### The problem

Running v 1.1.0 on 2023.8.2

Might have missed this one as it's related to https://github.com/frenck/spook/issues/262

Thanks

```
Logger: homeassistant.helpers.entity
Source: helpers/entity.py:1004
First occurred: 3:41:27 PM (1 occurrences)
Last logged: 3:41:27 PM

Entity event.repair (<class 'custom_components.spook.ectoplasms.repairs.event.RepairsSpookEventEntity'>) is implicitly using device name by not setting its name. Instead, the name should be set to None, please report it to the custom integration author.
```

**Comment by frenck** [comment]
Nice! Thanks for reporting that @Anto79-ops 👍 

../Frenck
