### ISSUE TITLE
Enable Entity is missing

### ISSUE THREAD

**Issue by sirbooker** [frenck/spook#34]
under services, it says you can enable/disable an entity, but I have found the enable feature to be missing while trying to create an automation.  (homeassistant.enable_entity)

**Comment by frenck** [comment]
🤷 Anything in the log?

Just saying: My car doesn't start, isn't something anyone can work with in a text message.

**Comment by sirbooker** [comment]
sorry...
the selection is not there to choose
![enable](https://user-images.githubusercontent.com/16746210/222992309-eefde40a-7061-4a4f-9bd7-547edb7c0cf1.png)

**Comment by frenck** [comment]
Thanks, that screenshot did put me in the right direction, found the issue and fixed it

![image](https://user-images.githubusercontent.com/195327/223052597-0c83e12c-67af-4122-b96b-3c01c2059cf2.png)

**Comment by sirbooker** [comment]
Thanks Franck

**Comment by frenck** [comment]
No problem 👍
