### ISSUE TITLE
Translation error?

### ISSUE THREAD

**Issue by tigers75** [frenck/spook#390]
### What version of Spook are you using?

1.3.0

### What version of Home Assistant are you using?

2023.10.0

### The problem

Many of the reports of spook lack both the info on the error and the link to fix it, like this:
![image](https://github.com/frenck/spook/assets/37505492/566111b0-d104-4055-a14a-eadf667d7de3)

It says it's a translation error, but still it looks like the placeholder for the variable is there.
I tried to take a look at the translations and all the strings seem to be there, what can I do to fix this? Should I do something special with the translation tool to get the variable recognized as such?

**Comment by tigers75** [comment]
Any news on this? I have to switch to English to have an usable add-in. I'd be glad to translate, but it's still locked even if the latest release says it updated translations.

**Comment by frenck** [comment]
Fixed in #428

**Comment by tigers75** [comment]
Hi, I don't think that this specific issue is fixed: #428 merges the translations, but there are errors that are still there; in this image you can see that the field within {} is substituted by a fixed string in the translation:
![image](https://github.com/frenck/spook/assets/37505492/eca75247-4b49-4c14-a32b-89c9ace463f1)

As I can see the translations can be modified now, so I'll try to fix as much as I can, so hopefully next release will be correct in italian too.

**Comment by lcavalli** [comment]
Yes, same issue here. Screenshots in English and Italian:

![Screenshot_20240105-135521](https://github.com/frenck/spook/assets/6123641/cf498b78-dd78-4448-bdd5-6cf4e6fa2592)

![Screenshot_20240105-135548](https://github.com/frenck/spook/assets/6123641/685f235b-985c-48ef-bc75-3128a5803819)

It seems a translation issue.
