### ISSUE TITLE
Incorrect Unknown Devices Reported

### ISSUE THREAD

**Issue by c0nt4x** [frenck/spook#415]
### What version of Spook are you using?

v1.3.1

### What version of Home Assistant are you using?

2023.10.5

### The problem

I have created 4 new automations today and Spook has notified 'Unknown Devices' errors in all 4 automations. However, all devices/entities used in the 4 automations do exist in my HA instance and are spelled correctly. One example below:

![image](https://github.com/frenck/spook/assets/70321584/003d80ba-d8aa-4bed-82fe-1a27166fcba6)

**Comment by frenck** [comment]
`light.office_lights` is an entity, not a device. The error is thus correct, as `light.office_lights` can never be a device...

Devices in automation look like a hash of random letters and numbers. Seems like your are mixing up things and Spook reports it :)

../Frenck

**Comment by c0nt4x** [comment]
> `light.office_lights` is an entity, not a device. The error is thus correct, as `light.office_lights` can never be a device...
> 
> Devices in automation look like a hash of random letters and numbers. Seems like your are mixing up things and Spook reports it :)
> 
> If you still think think Spook is incorrect, can you share the part of the automation you think it is flagging incorrectly?
> 
> ../Frenck

Ah yes I’d accidentally put device_id instead of entity_id in the actions. Thanks Frenck.
