### ISSUE TITLE
Translation error in repair

### ISSUE THREAD

**Issue by DurgNomis-drol** [frenck/spook#458]
### What version of Spook are you using?

1.3.2

### What version of Home Assistant are you using?

2023.11.3

### The problem

GIves an translation error when trying to use title field with `repair.create` service.
![Skærmbillede 2023-11-29 181246](https://github.com/frenck/spook/assets/67142049/ae9ba925-631f-4502-8465-f29470a5ba72)

### Anything in the logs? Paste it here!

```plain text
No error in the logfile
```

**Comment by frenck** [comment]
Thanks for sharing this one! This is being fixed by: #458
