### ISSUE TITLE
extra file in `custom_component` folder - spook inverse

### ISSUE THREAD

**Issue by Anto79-ops** [frenck/spook#484]
### What version of Spook are you using?

1.4.0

### What version of Home Assistant are you using?

2023.12.2

### The problem

hi, not sure if this is an issue or not but noticed an extra file called `spook_inverse` that is outside the Spook folder in the `custom_compoents` folder

![image](https://github.com/frenck/spook/assets/79593761/733fc4d8-103d-49d0-82be-31f5f696163b)

thanks for the integration.

**Comment by frenck** [comment]
Yup, that is correct, this is managed by Spook (hence the prefix).

../Frenck
