### ISSUE TITLE
trouble with translation to russian language

### ISSUE THREAD

**Issue by Shemmmy** [frenck/spook#531]
### What version of Spook are you using?

1.4.0

### What version of Home Assistant are you using?

2024.1.0

### The problem

Terrible translation problems. Some sections are not translated - a translation error message appears, and where there is a translation - it would be better not to have it, the writing is complete nonsense. Someone took a very creative approach to localization :))
![image](https://github.com/frenck/spook/assets/66095040/bdb80189-e9df-41ec-a3af-1c9645d79516)
![image](https://github.com/frenck/spook/assets/66095040/e4c52fd3-fc9c-4b80-a19f-7265b6280544)

**Comment by saintman23** [comment]
same here...
![изображение](https://github.com/frenck/spook/assets/11691558/22ab766c-e78a-4aad-9793-91b436850dba)

**Comment by frenck** [comment]
Fixed in #566

**Comment by Shemmmy** [comment]
In any case, the localization problem still persists: the links are not displayed as they do in the English locale.
I'm not even talking about translated words that are generated by neural networks and are not in Russian, like "дружка" :)
![spook](https://github.com/frenck/spook/assets/66095040/b17b8e24-c157-46d4-8bcf-b6c3c81aabb3)

**Comment by frenck** [comment]
This issue is closed, please consider creating a new issue if you find something.
