### ISSUE TITLE
Setup of sensor platform spook is taking over 10 seconds.

### ISSUE THREAD

**Issue by codyc1515** [frenck/spook#538]
### What version of Spook are you using?

v1.4.0

### What version of Home Assistant are you using?

core-2024.1.2

### The problem

Setup of sensor platform spook is taking over 10 seconds. It's not clear to me why that might be.

### Anything in the logs? Paste it here!

```plain text
Logger: homeassistant.components.sensor
Source: runner.py:188
Integration: Sensor (documentation, issues)
First occurred: 09:37:26 (1 occurrences)
Last logged: 09:37:26

Setup of sensor platform spook is taking over 10 seconds.
```

**Comment by frenck** [comment]
The problem with this message from Home Assistant is: If it often not caused by the integration reporting it :(

**Comment by codyc1515** [comment]
Thank you for the prompt reply. I had suspected as much.
