### ISSUE TITLE
Spook sensors should have state_class: measurement instead of total

### ISSUE THREAD

**Issue by rrozema** [frenck/spook#582]
### What version of Spook are you using?

v2.1.1

### What version of Home Assistant are you using?

2024.1.6

### The problem

The sensors created by Spook all seem to have a state_class: total attribute. This means the recorder creates statistics for them that have has_sum = 1 and has_mean = 0. has_sum = 1 however is to be used for sensors that have an increasing value, like f.e. energy usage, gas usage, costs, etc. The proper state_class on Spook's sensors would be measurement, so that more meaningful statistic min, max and mean values will be recorded for them.

**Comment by frenck** [comment]
You are now creating a definition based from some values you want.

Looking at the definition, these are totals.

**Comment by rrozema** [comment]
I am not creating this definition: The blog post [New sensor state class: total](https://developers.home-assistant.io/blog/2021/09/20/state_class_total/) dated September 20, 2012 by Erik Montnémery describes the intended use for the 3 available state_class: values:

- state_class: measurement - "_the state represents a measurement in present time_". This exactly matches the properties of Spook's sensors.
- state_class: total - "_a total amount that can both increase and decrease_". As you stated, this can be interpreted to match Spook's sensors, but only if you disregard the fact that we're talking about a change over some interval when looking at the statistics(_short_term) table.
- state_class: total_increasing - "_a monotonically increasing total_". This clearly does not match Spook's sensors.
I do not disagree that state_class: total can be read as a match. I just think that a "measurement in present time" is a better match when state_class: measurement would also result in a value stored in the statistics.[state] column, like with state_class: total. Hence my suggestion in my previous post. I don't see how the increase or decrease of these measurements over an interval -as stored in the statistics.[sum] column when state_class: total is specified- is meaningful. Especially after the short-term statistics have been purged and only the hourly values remain with no mean, min and max values remaining to describe if and/or what changes were made inside the hourly interval.

**Comment by frenck** [comment]
Sorry you are wrong.

The current value represents a total and not a measurement.

The currently set state class is correct.

../Frenck

**Comment by rrozema** [comment]
So it is a total because you've counted the number of objects? Counting a number of items is a measurement. For example: counting the number of lines the fluid inside a thermometer rose does not result in a _total_ for degrees celcius. No, that is called a measurement. How is counting those lines different than counting f.e. the number of sensors in my installation?

**Comment by frenck** [comment]
Sorry, thanks for the suggestion. This change won't be happening.

Thanks 👍 

../Frenck
