### ISSUE TITLE
Error while parsing localized (ru) string component.spook.issues.script_unknown_entity_references.description

### ISSUE THREAD

**Issue by avbor** [frenck/spook#610]
### What version of Spook are you using?

2.2.0

### What version of Home Assistant are you using?

2024.2.1

### The problem

Logger: homeassistant.helpers.translation
Source: helpers/translation.py:279
First occurred: 15:55:49 (1 occurrences)
Last logged: 15:55:49

Error while parsing localized (ru) string component.spook.issues.script_unknown_entity_references.description

### Anything in the logs? Paste it here!

HA language set to Russian

**Comment by frenck** [comment]
Thanks for reporting! Fixed in https://github.com/frenck/spook/pull/611

Will be part of the next release

../Frenck

**Comment by avbor** [comment]
Thanks!
