### ISSUE TITLE
Empty string for device triggers a repair (should be fixed)

### ISSUE THREAD

**Issue by mdehaas** [frenck/spook#619]
### What version of Spook are you using?

2.2.2

### What version of Home Assistant are you using?

2024.2.1

### The problem

When using Awesome Blueprints with optional values depending on using ZHA of Z2M the content of the optional value is defined as '' in the blueprint. This triggers a repair. This behaviour should be fixed in #499 following the issues #369 and #516
Is this a regression more people are seeing? These repairs where generated 20 hours ago, I don't know if I had the latest version at that time or the previous version. I've removed and reinstalled Spook but the repairs persist.

**Comment by caraar12345** [comment]
Came here to report the same - only popped up after upgrading to 2.2.2 as far as I can tell.

**Comment by Cereal2nd** [comment]
Seeing the same thing, also with awesome blueprints.

![afbeelding](https://github.com/frenck/spook/assets/3715825/7eb95641-888e-4204-a2dd-46abad44debd)
![afbeelding](https://github.com/frenck/spook/assets/3715825/86bc0eb8-7ab3-49af-aba6-96a9528b4e3c)

**Comment by drueppela** [comment]
Disclaimer:

Spook was one of the most missing tiles in Home Assistant.I hope Spook to be merged in Home Assistant Core and I hope Spook will make its way to be the all-seeing Trash Heap

https://www.google.com/search?q=all-seeing+Trash+Heap&sourceid=chrome&ie=UTF-8

@frenck 🥇: I am in IT / Business Development for 30 years. Some say I am old. Some say I am experienced. If I can contribute from another angle .... I would be glad to join.

Here my two cent regarding https://github.com/frenck/spook/issues/619:

Home Assistant

Core: 2024.2.5
Supervisor: 2024.02.1
Operating System: 12.0
Frontend: 20240207.1
Spook: Always Bleeding Edge


![image](https://github.com/frenck/spook/assets/9786634/787797d1-c642-47e9-8679-2e966de9f6e5)
