### ISSUE TITLE
Input number increase/decrease has issues with the step value

### ISSUE THREAD

**Issue by Ladonize** [frenck/spook#62]
input number increase/decrease isn't working: When using it without the new amount option I get this error: 

>  File "/config/custom_components/spook/services/input_number_increment.py", line 31, in async_handle_service
>   if (amount := call.data.get("amount", entity.step)) % entity.step != 0:
> AttributeError: 'InputNumber' object has no attribute 'step'

Even thought the input number has a step (and min/max) configured (through the UI).

When i try to call the service with explicitly setting the new amount value I get this (with both a whole number and a decimal): 
> Error handling message: extra keys not allowed @ data['step']. Got None (invalid_format)

One of my input numbers has a decimal step configured, min: 0.1, max 1, step 0.1. The dev tools/service UI shows a red line under the input field when I enter a decimal number, but it does allow me to save it.

**Comment by frenck** [comment]
Thanks! Fixed in #64
