### ISSUE TITLE
Spook not HUE's hoomie

### ISSUE THREAD

**Issue by itchensen** [frenck/spook#623]
### What version of Spook are you using?

2.2.2

### What version of Home Assistant are you using?

2024.2.1

### The problem

I have an automation using a HUE service call (hue.activate_scene) working fine. 
In the past, Spook also was fine with it, but since one of the last updates, i get an repair issue pointing out, that hue.activate_scene isn't known by home assistant. It remains with the latest update to 2.2.2

As pointet out: It is available, i can use ist in the DEV-Tools Service Tab and also the automation is working fine. The service call is the official one documented here: [HUE Integration](https://www.home-assistant.io/integrations/hue/)

For me, it seems like a false positive, would you mind having a look at it? Thank's alot in advance!

### Anything in the logs? Paste it here!

The logs don't show up anything.

**Comment by djmvt** [comment]
Getting the same issue since a few days. Automation working fine but spook reports an unknown service when calling hue.hue_activate_scene
