### ISSUE TITLE
Repair: Available entities are announced as unavailable.

### ISSUE THREAD

**Issue by HaraldGithub** [frenck/spook#627]
### What version of Spook are you using?

2.2.2 (latest)

### What version of Home Assistant are you using?

2024.2.2

### The problem

Hi @frenck 
Since the last Update of spook I've a similar issue:
I got this repair announcement about an unknown entity:
<img width="595" alt="image" src="https://github.com/frenck/spook/assets/90566183/82ba6bfd-3883-4f55-8f2f-6e12d9d7810d">
but in developper tools this entity is known:
<img width="1010" alt="image" src="https://github.com/frenck/spook/assets/90566183/c729eedf-3302-4b03-8a02-29e161d93330">
and in "Overview" it is also available:
<img width="335" alt="image" src="https://github.com/frenck/spook/assets/90566183/90947b78-a369-4fc6-a7ea-ec8ec6916c49">
I've received this message after restart from update from 2024.2.1 to 2024.2.2.

In former times, and also before last spook-update, I've received this message, too, but it was gone some seconds after restart of HA. On restart of HA, an automation will also restart the samba-addon, so for few seconds it might be possible, that spook recognize this entity as unavailable. But after the restart of the add-on it's available (as you can see in screen shots above).
I think it's a bug in the last spook-update.

### Anything in the logs? Paste it here!

```plain text
About this issue, there aren't any logs.
```

**Comment by berendhaan** [comment]
I'm having the same issue, spook doesn't seem to clean-up issues after a sensor becomes available again.

I don't think posting a screenshot will help, are there some hints in the log you could use?

**Comment by HaraldGithub** [comment]
> are there some hints in the log you could use?

See above, there are no hints in the log's. ;-)

**Comment by bkbartk** [comment]
same here,
an entity got a new name, changed this in the automation but the message keeps showing the old sensor which isn't used anymore.
the messages for dashboard however got cleaned up.

**Comment by AlexKusnezov** [comment]
same here, a sensor, which was used in several automatiions, was for couple of seconds unavailable due to reboot. Now it's avsilable and updating since four hours. Repairs are still there...

**Comment by dxmnkd316** [comment]
oddly enough this morning I had a hard reboot due to another issue that popped up and the entities are now working again.  not sure what was different this time.

**Comment by jokerigno** [comment]
same issue..repairs are not removed when fixed

**Comment by pvmil** [comment]
I really like spook, it helped me resolve several issues.
I do however have the same issue (as reported in the initial message) with the sensor.samba_backup, can I provide additional information on this?

**Comment by frenck** [comment]
Which integration provides `sensor.samba_backup`?

../Frenck

**Comment by pvmil** [comment]
> Which integration provides `sensor.samba_backup`?
> 
> ../Frenck

https://github.com/thomasmauerer/hassio-addons/tree/master/samba-backup

**Comment by frenck** [comment]
That is an add-on, which integration is it using for entities?

**Comment by frenck** [comment]
Aaah it isn't using an integration...

https://github.com/thomasmauerer/hassio-addons/blob/master/samba-backup/rootfs/scripts/sensor.sh

That is an upstream issue, as this is not the proper way to integrate with Home Assistant.


Closing on this end.
