### ISSUE TITLE
Date format doesn't follow locale setting, it appears hard coded to the American format month/day/year

### ISSUE THREAD

**Issue by dnedeltchev** [frenck/spook#642]
### What version of Spook are you using?

2.2.2

### What version of Home Assistant are you using?

2004.2.3

### The problem

Date format is the American one, month/day/year which is confusing. Ideally it should follow the locale of home assistant.

**Comment by frenck** [comment]
Which date format are you talking about?

**Comment by dnedeltchev** [comment]
The notification for repairs. This one is regarding non-existent entities
in one of my groups. The date at the bottom is the American format
mm/dd/yyyy.

**Comment by frenck** [comment]
That is not a Spook thing. 

Closing the issue on this end for that reason.


../Frenck
