### ISSUE TITLE
Issues with automations do not survive a reboot 

### ISSUE THREAD

**Issue by danielsza** [frenck/spook#668]
### What version of Spook are you using?

2.2.2.

### What version of Home Assistant are you using?

2024.3.3

### The problem

If a problem is found with a (or multiple) automation(s) and home assisant is rebooted. The automation no longer appears in the list of problems. In "Automations & scenes" the offending automations appears in red. 
![ha](https://github.com/frenck/spook/assets/6549750/86c4aa82-b328-414b-a365-d1508031b327)

**Comment by frenck** [comment]
> In "Automations & scenes" the offending automations appears in red.

That means the automation isn't valid for loading; so Home Assistant skipped that automation.

Spook will not report on that, as there is nothing to report on (the automation isn't there).

../Frenck

**Comment by danielsza** [comment]
But prior to a reboot spook does show that there is an issue with automation. If the error occurred prior to the first reboot.

For example if I remove e device, spook will show all automations that use that device as having an issue. However if I reboot those errors no longer show up.

**Comment by frenck** [comment]
> But prior to a reboot spook does show that there is an issue with automation. 

Spook analyzes automations for issues that are in Home Assistant. In this case, this automation cannot be parsed even by Home Assistant and isn't loaded. If it ain't loaded, there is nothing to analyze for Spook.

../Frenck
