### ISSUE TITLE
Results with fixing inconsistent, no bug but could be improved.

### ISSUE THREAD

**Issue by VictoriousCupid** [frenck/spook#68]
When missing entities in automation are fixed by altering the automation Spook does dismiss the repair issue.
When missing devices in automation are fixed by altering the automation Spook does NOT dismiss the repair issue. (doesn't reproduce after reboot)
When missing entities or device in automation is fixed by deleting the automation Spook does NOT dismiss the repair issue. (doesn't reproduce after reboot)

**Comment by frenck** [comment]
I'm lost on what you are trying to say?

Could you write a bit more clearly what you mean?

**Comment by VictoriousCupid** [comment]
Let me try. When spook raises a repair for a missing entity or device in an automation you can go into the automation and do what is needed to fix it.
Either you alter the automation or you delete the automation.

1 When there is an entity mentioned in an automation that doesn't exist anymore you fix that by altering the automation.
When you do this the repair is resolved. 
2 When this situation is identical but with a missing device the repair doesn't get resolved.
3 When you delete the automation instead it doesn't get resolved either. 

And now that I am writing this down I start to wonder... is it spook that resolves the repair or is that something that HA does? Maybe I'm addressing this in the wrong place...

**Comment by frenck** [comment]
There is nothing to be done about that. At runtime, there is still a reference (even after you have removed it from the automation). Restarting Home Assistant is the only way to resolve it. Meanwhile, Spook will (at least) try picking up the changes to the extend possible.
