### ISSUE TITLE
recorder.import_statistics always requires last_reset

### ISSUE THREAD

**Issue by gerard33** [frenck/spook#72]
When using `recorder.import_statistics` there is an error when the `last_reset` field is not used in the stats: `Invalid datetime specified: None for dictionary value @ data['stats'][0]['last_reset']. Got None`

When entering a date for `last_reset` the service is working.

That field is not mandatory but due to the [cv.datetime check](https://github.com/frenck/spook/blob/main/custom_components/spook/services/recorder_import_statistics.py#L34) with the default None value this seems to be going wrong.

**Comment by frenck** [comment]
Nice catch! Thanks 👍 

<img src="https://media1.giphy.com/media/l41lZuDtMj71VOHxS/giphy.gif"/>

../Frenck
