### ISSUE TITLE
False positive: binary_sensor.backups_stale is reported as missing after home assistant restart

### ISSUE THREAD

**Issue by RolandBoeni7098** [frenck/spook#725]
### What version of Spook are you using?

2.2.4

### What version of Home Assistant are you using?

2024.3.3

### The problem

binary_sensor.backups_stale is reported as missing directly after home assistant restart. This is a sensor provided by "Home Assistant Google Drive Backup". The sensor exists after a short time period. I don't know exactly how long it takes for the add-on to create the sensor.

**Comment by frenck** [comment]
This addon is injecting states into Home Assistant. This is incorrect practice. It should use/make an integration instead.

Closing, as this is not an issue with Spook, but an issue with what they do. Please report the issue with them.

../Frenck
