### ISSUE TITLE
Detected blocking call to import_module inside the event

### ISSUE THREAD

**Issue by cloudbr34k84** [frenck/spook#743]
### What version of Spook are you using?

2.2.4

### What version of Home Assistant are you using?

2024.5.0b0

### The problem

Logger: homeassistant.util.loop
Source: util/loop.py:99
First occurred: 9:41:55 am (107 occurrences)
Last logged: 9:42:27 am

Detected blocking call to import_module inside the event loop by custom integration 'spook' at custom_components/spook/util.py, line 55: module = importlib.import_module(f".{module_path}", __package__) (offender: /config/custom_components/spook/util.py, line 55: module = importlib.import_module(f".{module_path}", __package__)), please create a bug report at https://github.com/frenck/spook/issues
Detected blocking call to import_module inside the event loop by custom integration 'spook' at custom_components/spook/templating.py, line 122: module = importlib.import_module(f".{module_path}", __package__) (offender: /config/custom_components/spook/templating.py, line 122: module = importlib.import_module(f".{module_path}", __package__)), please create a bug report at https://github.com/frenck/spook/issues
Detected blocking call to import_module inside the event loop by custom integration 'spook' at custom_components/spook/services.py, line 272: module = importlib.import_module(f".{module_path}", __package__) (offender: /config/custom_components/spook/services.py, line 272: module = importlib.import_module(f".{module_path}", __package__)), please create a bug report at https://github.com/frenck/spook/issues
Detected blocking call to import_module inside the event loop by custom integration 'spook' at custom_components/spook/util.py, line 76: module = importlib.import_module(f".{module_path}", __package__) (offender: /config/custom_components/spook/util.py, line 76: module = importlib.import_module(f".{module_path}", __package__)), please create a bug report at https://github.com/frenck/spook/issues
Detected blocking call to import_module inside the event loop by custom integration 'spook' at custom_components/spook/repairs.py, line 276: module = importlib.import_module(f".{module_path}", __package__) (offender: /config/custom_components/spook/repairs.py, line 276: module = importlib.import_module(f".{module_path}", __package__)), please create a bug report at https://github.com/frenck/spook/issues

**Comment by frenck** [comment]
duplicate of #681 and #740, fixed by #722
