### ISSUE TITLE
Google Backup Entities

### ISSUE THREAD

**Issue by duczz** [frenck/spook#750]
### What version of Spook are you using?

3,0,1

### What version of Home Assistant are you using?

2024.04.4

### The problem

These two entities are many times popup up, but these entities are ok, maybe you can check these (in my system only these two are often wrong reporting)
![image](https://github.com/frenck/spook/assets/25475385/91ba5b06-734b-4c3c-9076-4adc8e8edd99)

**Comment by duczz** [comment]
Google Drive Backup Integration

**Comment by frenck** [comment]
Can you point me to the place where I can find that integration?

**Comment by duczz** [comment]
Sure, addons > Home Assistant Google Drive Backup

**Comment by frenck** [comment]
@duczz That is not an integration, but an add-on.

Considering your answer, I know what is going on. This add-on injects states into the state machine. It should not be doing that, instead, the add-on should provide an actual integration.

This is not a supported (nor a correct) use of Home Assistant and not something I can do anything about. Please report the issue with the Google Drive Backup integration instead.

../Frenck
