### ISSUE TITLE
Unable to use step value for number.decrement/increment service

### ISSUE THREAD

**Issue by qp68** [frenck/spook#78]
Same issue as in #62 but for number.decrement and number.increment services.

I'm unable to use these services when specifying a step, receive following error :
> Error handling message: extra keys not allowed @ data['step']. Got None (invalid_format)

**Comment by frenck** [comment]
This is not related to #62, but an user-error.

`step` isn't a valid parameter for this service call.

../frenck

**Comment by frenck** [comment]
That is amount, not step.

**Comment by frenck** [comment]
Aah I see the issue, ok, thanks! Will fix that!

**Comment by frenck** [comment]
Fixed in current main branch, will be part of the next release.
