### ISSUE TITLE
Generating abundant async_delete_issue

### ISSUE THREAD

**Issue by Mariusthvdb** [frenck/spook#783]
### What version of Spook are you using?

3.0.1
I have all devices disabled and only use the repairs creation of Spook

### What version of Home Assistant are you using?

2024.7.0b2

### The problem

debugging with @bdraco we found this:

> probably should get an issue for that
> fl=/config/custom_components/spook/repairs.py
> fn=_async_inspect
> Its spook hat generates all be 20x of them

![delete_issue_over_and_over](https://github.com/frenck/spook/assets/33354141/09251fc7-dd45-4bf3-a46a-ffc679726cf5)

### Anything in the logs? Paste it here!

not really sure why to add, as I am not technically advanced enough to describe it better than above.
Maybe Nick can add if required

**Comment by bdraco** [comment]
The issue is the 1000x calls to `async_delete_issue` per minute

**Comment by frenck** [comment]
Yup! It ensures the issue no longer exists. This is by design.

Alternatively, I could look up if the issue exists, which will just move the load elsewhere.

../Frenck
